export * from "./adapter.ts";
export * from "./path.ts";
export * from "./version.ts";
export * from "./queue.ts";
export * from "./tools.ts";
export { claudeAdapter, probeClaude } from "./claude/index.ts";
export { codexAdapter, probeCodex } from "./codex/index.ts";
export { JsonRpcChild } from "./codex/rpc.ts";
export { ompAdapter, probeOmp } from "./omp/index.ts";
import type { HarnessKind } from "@beam/contracts";
import type { HarnessAdapter } from "./adapter.ts";
import { claudeAdapter } from "./claude/index.ts";
import { codexAdapter } from "./codex/index.ts";
import { ompAdapter } from "./omp/index.ts";
export const adapters: Record<HarnessKind, HarnessAdapter> = { claude: claudeAdapter, codex: codexAdapter, omp: ompAdapter };
